### ISSUE TITLE
If data.table is installed then use fread to speed up the loading times of csv files

### ISSUE THREAD

**Issue by majkamichal** [el-meyer/airship#138] opened 2023-12-02 17:38 UTC
Currently, loading of `ExampleDataFACTS.csv` with 66mb takes 12-15 seconds on my MacBook Air M1.

--> When using `data.table::fread` the loading time gets reduced to about 3 seconds.

On top of that there is further processing of the data and takes additional seconds.

The `data.table` package will be in suggested packages, and if installed, it will be automatically be used.

**Comment by majkamichal** [comment] 2023-12-04 15:16
I thought that `data.table::fread( ... , data.table = FALSE)` outputs always a `data.frame` object. Interesting...

**Comment by el-meyer** [comment] 2023-12-04 16:05
Maybe the problem is not `data.frame` vs `data.table`, because there are still instances where "Summarized Data" is simply not showing when the data was imported using fread. Interesting, I will investigate further.

**Comment by el-meyer** [comment] 2023-12-04 16:09
Yes I agree that seems the most likely case, I already fixed the fact that whitespace is coded as whitespace in fread but "." in read.csv

**Comment by el-meyer** [comment] 2023-12-05 07:46
The difference between uploading the data and supplying via command line are in lines 713-789.

**Comment by el-meyer** [comment] 2023-12-05 12:11
fread also breaks "Convert -9999 to NA" feature. 

To reproduce: Upload any FACTS data, button has no effect. Change line 719 to "FALSE" (i.e. use read.csv) and then it works.

**Comment by el-meyer** [comment] 2023-12-05 14:16
Until this feature fully works, it has been deactivated in line 166.

**Comment by majkamichal** [comment] 2023-12-15 16:13
It is indeed strange. 
It looks like the underlying dataset is properly manipulated and all missing values are removed.
The data table, however, is not updating.

When one uploads `ExampleFACTS2` to the app, then clicks on the "Use example dataset", and then goes back to "Use FACTS..." then the table is updating and no missing values coded as `-9999` are visible.

**Comment by el-meyer** [comment] 2023-12-15 18:44
Very strange. This would certainly not be an elegant solution, but maybe if the object was copied-by-value to a different object before it might work?

**Comment by majkamichal** [comment] 2023-12-15 18:57
I am not sure. We can definitely try.

**Comment by majkamichal** [comment] 2023-12-15 19:36
I created a regular table based on `tableOutput()` and `rednerTable()`, outputted `upload()` and the finding is that the same issue persists. The regular table is also not properly updated.

So it is not only `DT` related.

**Comment by majkamichal** [comment] 2023-12-15 19:45
Ok! The issue is fixed when I use `check.names = TRUE` in `data.table::fread`.

It is updating normally. This parameter is also set to `TRUE` in `read.csv` (which is a wrapper to `read.table` in which there is that setting set by default to `TRUE`)

I will create a pull request soon.

**Comment by majkamichal** [comment] 2023-12-15 20:05
It looks now that column names are exactly the same, as long as the last empty column is removed.
It makes sense, both `read.csv` and `fread` use the same parameter `check.names=TRUE`.

`library(airship)`
`df1 <- airship::fnReadFacts("data/ExampleDataFACTS2.csv", bUseFread = FALSE)`
`df2 <- airship::fnReadFacts("data/ExampleDataFACTS2.csv", bUseFread = TRUE)`

`ind <- colnames(df1) == colnames(df2)`
`ind`

`cbind(read.csv = colnames(df1),`
`      fread = colnames(df2),`
`      equal = ind)`


> ind
  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [13] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [25] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [37] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [49] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [73] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [85] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [97] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[109] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

**Comment by el-meyer** [comment] 2023-12-15 20:15
That's amazing, thanks Michal!

**Comment by el-meyer** [comment] 2023-12-15 20:18
I will test after the merge and close this issue if everything looks fine.

**Closed** 2023-12-15 21:07 UTC
Labels: bug, enhancement
